### ISSUE TITLE
项目咨询

### ISSUE THREAD

**Issue by muyuuuu** [willard-yuan/mlflow#2]
某天在我的 github 主页看到了这个项目，出于兴趣点开了链接。

发现代码的注释很少，doc 也在施工中，大概可以通过文件名、变量名推测一二。

可以问一下这个项目更多的细节嘛？如应用场景，针对的用户，后期的发展，或者哪里需要帮忙，我可以学业之余看一看（其实是我也想写一些这方面的程序。

**Comment by willard-yuan** [comment]
@muyuuuu 感谢对这个项目有兴趣。这个项目主要是想做偏应用型的工具流，项目来源我的另外一个项目[cvtk](https://github.com/willard-yuan/cvtk)。由于之前工作原因，就把做的computer vision上偏应用的方案整理成一个工具集合。目前做搜索、nlp方面的工作比较多，然后我就在想，能不能也像之前一样，把平时工作中一些应用方案积累下来，构成一个应用型Machine Learning工具集，方便日后自己、他人的工作。

如果你有兴趣或者对开源项目感兴趣，想向[Davis E. King](https://github.com/davisking)或者[Matthijs Douze](https://github.com/mdouze)这些大佬一样，开发出来有影响力的开源作品，我们可以一起探讨。

可以发邮件保持联系。
